name: build images

on:
  push:
    tags: []
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  get-vars:
    runs-on: ubuntu-latest
    env:
      IMAGES_PATH: ./images
    outputs:
      images: ${{ steps.detect-changes.outputs.changes }}
      imagesPath: ${{ env.IMAGES_PATH }}
      registry: ghcr.io
      tagPrefix: images
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - id: get-all-images
        name: Get image names
        uses: philips-labs/list-folders-action@v2
        with:
          path: ${{ env.IMAGES_PATH }}
      - id: prepare-filters
        run: |
          filters='${{ steps.get-all-images.outputs.folders }}' | jq 'INDEX(.) | map_values(["\(.)/**" ])'
          echo $filters
          echo "filters=$filters" >> "$GITHUB_OUTPUT"
      - uses: dorny/paths-filter@v3
        id: detect-changes
        with:
          working-directory: ${{ env.IMAGES_PATH }}
          filters: ${{ fromJson(steps.prepare-filters.outputs.filters) }}

  call-build-workflow:
    if: ${{ github.ref_type != 'tag' }}
    needs: [get-vars]
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.get-vars.outputs.images) }}
    uses: ./.github/workflows/image-build.yml
    with:
      registry: ${{ needs.get-vars.outputs.registry }}
      name: ${{ matrix.image }}
      context: ${{ needs.get-vars.outputs.imagesPath }}/${{ matrix.image }}/src

  call-publish-workflow:
    if: ${{ startsWith(github.ref, needs.get-vars.outputs.tagPrefix) }}
    needs: [get-vars]
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.get-vars.outputs.images) }}
    uses: ./.github/workflows/image-publish.yml
    with:
      tagPrefix: ${{ needs.get-vars.outputs.tagPrefix }}
      registry: ${{ needs.get-vars.outputs.registry }}
      name: ${{ matrix.image }}
