name: build image

on:
  workflow_call:
    inputs:
      name:
        description: image name
        required: true
        type: string
      context:
        description: build context
        required: true
        type: string
      registry:
        description: registry
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.event.inputs.registry }}/${{ github.event.inputs.name }}
          tags: |
            type=sha,prefix=,format=long,priority=2000
            type=sha,prefix=
            type=sha,prefix=${{ github.head_ref || github.ref_name }}-,format=short
            type=raw,value=${{ github.head_ref || github.ref_name }}
            type=edge
          flavor: |
            latest=false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export to docker
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.event.inputs.context }}
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
      - name: Test
        run: |
          docker run --rm ${{ fromJson(steps.meta.outputs.json).tags[0] }}
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ github.event.inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: |
          docker push --all-tags ${{ fromJson(steps.meta.outputs.json).tags[0] }}
